name: presc
channels:
  - conda-forge
dependencies:
  - confuse=1.7.0
  - flake8=4.0.1
  - numpy=1.22.3
  - pandas=1.4.1
  - python=3.9.10
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - jupyter-book=0.12.2
  - matplotlib=3.5.1
  - m2r2=0.3.2
  - seaborn=0.11.2
  - pip=22.0.4
  - plotnine=0.8.0
  - pre-commit=2.17.0
  - pytest=7.0.1
  - pytest-cov=3.0.0
  - pyyaml=6.0
  - sphinx=4.4.0
  - twine=3.8.0
  - catboost==1.0.6
  - pip:
    - sphinx-rtd-theme==1.0.0
    - idx2numpy==1.2.3
