name: presc
channels:
  - conda-forge
dependencies:
  - numpy=1.18.1
  - pandas=1.0.1
  - python=3.7.6
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - jupyter=1.0.0
  - matplotlib=3.1.3
  - seaborn=0.10.0
  - pip=20.0.2
  - pip:
    - plotnine==0.6.0
    - pytest==5.4.3
    - pytest-cov==2.10.0
    - twine==3.2.0
    - pre-commit==2.6.0
